<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>RF_SafetyScanner</AssemblyName>
    <RootNamespace>RF_SafetyScanner</RootNamespace>
    <Version>3.1.0</Version>
  </PropertyGroup>
</Project>
